### ISSUE TITLE
zip files not extractable

### ISSUE THREAD

**Issue by mzarvandi** [mansourehk/ShEMO#1]
Hi,

I am trying to download you dataset for my speech recognition task, but seems there's a problem with the male.zip and the female.zip files, as when I try to extract them it raises an error says: file.zip not an archive. Is something wrong with the uploaded files? I would appreciate if you could inform me.

**Comment by mansourehk** [comment]
Hi Maedeh, I downloaded both files again and were able to unzip them. I used the "Extract" option on windows.
If you are using WinRAR, maybe you can check the repair option before extracting it.
By the way, the dataset is also available on Kaggle ([link](https://www.kaggle.com/mansourehk/shemo-persian-speech-emotion-detection-database)).

**Comment by mzarvandi** [comment]
Thanks for the Kaggle link, it worked.

Regards,

**Comment by mansourehk** [comment]
Great and Good Luck
